image: registry.manatree.io/rvanduijnhoven/maven-python-dockerimage
variables:
  GIT_SUBMODULE_STRATEGY: recursive
  ZIP_PATH: releng/com.altran.general.integration.xtextsirius.repository/target

before_script:
  - chmod -R +x ./releng/scripts

stages:
  - build

Build maven projects:
  stage: build
  tags:
    - linux_docker
  script:
    - ./releng/scripts/build.sh $CI_COMMIT_REF_NAME $CI_COMMIT_TAG
  artifacts:
    when: always
    paths:
      - $ZIP_PATH/*.zip
